import { PrimeReactProvider } from 'primereact/api';

import "../css/globals.css";
import localFont from "next/font/local"

import { Navbar, Footer } from '../sections/index'
import PageBanner from "../components/PageBanner";

const fraunces = localFont({
  src: '../../public/fonts/FRAUNCES-REGULAR.woff2'
})

export const metadata = {
  title: "Mutual - Cases ",
  description: "Generated by create next app",
};


export default function MainLayout({ children, params }) {
    // const route = useRouter().pathname;
    console.log(params.section);
    

  return (
    <PrimeReactProvider>
      <div className={`${fraunces.className} `}>
          <PageBanner/>
          {children}
      </div>
    </PrimeReactProvider>
  );
}
