import { PrimeReactProvider } from 'primereact/api';

import "../css/globals.css";
import localFont from "next/font/local"

import { PageBanner, WarrantyBanner } from "../components/index";

const fraunces = localFont({
  src: '../../public/fonts/FRAUNCES-REGULAR.woff2'
})

export const metadata = {
  title: "Mutual - Cases ",
  description: "Generated by create next app",
};


export default function MainLayout({ children, params }) {
  return (
    <PrimeReactProvider>
      <div className={`${fraunces.className} relative`}>
          <PageBanner/>
          {children}
          <WarrantyBanner />
      </div>
    </PrimeReactProvider>
  );
}
