import "./css/globals.css";
import localFont from "next/font/local"

import GlobalErrorListeners from './components/GlobalErrorListeners'
import { ToastProvider } from './components/Toast/ToastProvider'
import { LikeProvider } from './Context/LikeContext'
import { CartProvider } from './Context/CartContext'
import { I18nProvider } from './i18n/I18nProvider'
import Chrome from './components/Chrome'

const fraunces = localFont({
  src: '../public/fonts/FRAUNCES-REGULAR.woff2'
})

export const metadata = {
  title: "Mutual - Cases & more",
  description: "Generated by create next app",
};

// Applied before paint so the language + RTL direction are set with no flash.
const themeScript = `(function(){try{
  var lang = localStorage.getItem('mutual_lang') || 'en';
  document.documentElement.setAttribute('lang', lang);
  document.documentElement.setAttribute('dir', lang === 'ar' ? 'rtl' : 'ltr');
}catch(e){}})();`

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={fraunces.className}>
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
      </head>
      <body className={`font-default`}>
        <GlobalErrorListeners />
        <I18nProvider>
          <ToastProvider>
            <LikeProvider>
              <CartProvider>
                <Chrome>{children}</Chrome>
                <script
                  src="https://accounts.google.com/gsi/client"
                  strategy="afterInteractive"
                />
              </CartProvider>
            </LikeProvider>
          </ToastProvider>
        </I18nProvider>
      </body>
    </html>
  );
}
