import "./css/globals.css";
import localFont from "next/font/local"

import GlobalErrorListeners from './components/GlobalErrorListeners'
import { ToastProvider } from './components/Toast/ToastProvider'
import { LikeProvider } from './Context/LikeContext'
import { CartProvider } from './Context/CartContext'
import Chrome from './components/Chrome'

const fraunces = localFont({
  src: '../public/fonts/FRAUNCES-REGULAR.woff2'
})

export const metadata = {
  title: "Mutual - Cases & more",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={fraunces.className}>
      <body className={`font-default`}>
        <GlobalErrorListeners />
        <ToastProvider>
          <LikeProvider>
            <CartProvider>
              <Chrome>{children}</Chrome>
              <script
                src="https://accounts.google.com/gsi/client"
                strategy="afterInteractive"
              />
            </CartProvider>
          </LikeProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
